version: '3.8'
services:
  app2:
    container_name: app2
    build: ./docker/php
    volumes:
      - .:/var/www
    depends_on:
      - db2

  nginx2:
    image: nginx
    container_name: nginx2
    ports:
      - "8100:80" # nginxのポートを変更
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app2

  db2:
    image: mysql:5.7
    container_name: db2
    environment:
      MYSQL_ROOT_PASSWORD: secret2
      MYSQL_DATABASE: database2
      MYSQL_USER: user2
      MYSQL_PASSWORD: pass2
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306" # MySQLのポートを変更
